### ISSUE TITLE
有oc版的吗小哥哥

### ISSUE THREAD

**Issue by Hynsen** [chenqihui/QHAwemeDemo#2]

**Comment by chenqihui** [comment]
Objective-C，你可以看这个 https://github.com/newyjp/JPNavigationController

**Comment by Hynsen** [comment]
想咨询下您的tabbar是怎么实现的呢？

**Comment by chenqihui** [comment]
是说实现啥？架构用的是QHTabBarController模块，不过这个随便写的，不完全，也不是主要的分享内容
