### ISSUE TITLE
咨询手势问题。

### ISSUE THREAD

**Issue by sea7reen** [chenqihui/QHAwemeDemo#3]
请问在demo中如何取消右滑的手势。

**Comment by chenqihui** [comment]
你是说首页的广告位？

**Comment by sea7reen** [comment]
是的，或者如果我想单独的取消右滑，或者取消左滑。我改在哪里设置。

**Comment by chenqihui** [comment]
首页广告页隐藏，有两个方法吧
1、针对 mainScrollV 设置 mainScrollV.isScrollEnabled = false 不可滑动，并只显示 right 区域，这是想保留右边待以后使用的方式
override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        mainScrollV.contentOffset = CGPoint(x: UIScreen.main.bounds.width, y: 0)
    }
2、将 rootVC 的 mainScrollV，只保留 rightVC，或者直接只使用 rootVC，都可以。这种是彻底去掉。

然后想取消，控制协议有对应的 API 可单独设置。

**Comment by sea7reen** [comment]
额。。还是没有改好。你能代码更改给我示例下吗？我拉去下。

**Comment by chenqihui** [comment]
1、的直接添加在 rootVC 就行，就是控制 UIScrollView

其实应该是 pod 这个模块来实现手势 push，不用 demo 就不会有 首页的页面架构了，毕竟它只是 Demo 需求的部分。

have fun

**Comment by sea7reen** [comment]
是这样在QHRootScrollView，目前PushBegin， PushEnd，ShouldPush，这3个方法右滑的时候都没有走，只有GesturePush。相对的左滑都会走。 mainScrollV.isScrollEnabled = false ，我设置了没效果。

**Comment by sea7reen** [comment]
方便加您微信或者QQ吗

**Comment by chenqihui** [comment]
哦哦，你在 QHRootScrollView 的 viewDidLoad 添加 mainScrollV.isScrollEnabled = false。你还需要将下面 ShouldPush 和 PushEnd 里面对应的 mainScrollV.isScrollEnabled = false 和 mainScrollV.isScrollEnabled = true 给去掉（这部分是对应需求的），还有 QHTabBarViewController 的 p_setTabBarViewColor 里面的也去掉，等于只保留 mainScrollV.isScrollEnabled = false 的一处控制。这部分就是首页的页面架构。
你可以这样试试，应该就可以了。

**Comment by sea7reen** [comment]
歇歇。我再看看您写的那些。我也是第一次做短视频的APP。
辛苦了~

**Comment by sea7reen** [comment]
pod 不下来这个？

**Comment by chenqihui** [comment]
search 看看，没有的话就 update 下 repo
