### ISSUE TITLE
进入视频播放界面返回 时deinit方法不执行

### ISSUE THREAD

**Issue by CoderST** [chenqihui/QHAwemeDemo#4]
进入视频播放界面返回 时deinit方法不执行,界面不释放,当录制界面全部退出后,QHRecordViewController和QHPlayViewController才一起释放.

**Comment by chenqihui** [comment]
Fix，你更新下，
QHRecordViewController 里面的 (self.navigationController as? QHNavigationController)?.changeTransition(true) 调用时机造成。

**Comment by CoderST** [comment]
谢谢,但是还是不太明白,这样问题虽然能解决,但是总感觉这样操作显得不友好,在录制界面返回后,先添加转场->返回操作->在关注转场.

**Comment by chenqihui** [comment]
哦哦，你可以用主要的 手势push 功能，而 自定义push动画 用回系统的 present 和 dismiss。

这个它目前需要绑定和取消的对应，可以根据自己项目那里设置妥就那里设，也可以先忽略不使用。（我现在也就只是先根据 Demo 调整调用下）

have fun！
