### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by CoderST** [chenqihui/QHAwemeDemo#5]
您好，很不好意思，来打扰您，我有一个问题想请教一下，在用您的这个框架时候，不太理解在QHNavigationController中，如下
if self.topViewController as! QHNavigationControllerProtocol
这句话不理解，为什么viewController和协议来做类型比较，
这句话转成oc怎么写呢？便于理解, 希望能收到您的回复，谢谢。

**Comment by chenqihui** [comment]
Objc ：((id\<QHNavigationControllerProtocol\>) self.topViewController) 大概这种，
进行类型声明
